/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminJourneysRouteImport } from './routes/admin.journeys'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJourneysRoute = AdminJourneysRouteImport.update({
  id: '/admin/journeys',
  path: '/admin/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/journeys': typeof AdminJourneysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/journeys': typeof AdminJourneysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/journeys': typeof AdminJourneysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/journeys'
    | '/admin/login'
    | '/admin/news'
    | '/news/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/journeys'
    | '/admin/login'
    | '/admin/news'
    | '/news/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/journeys'
    | '/admin/login'
    | '/admin/news'
    | '/news/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminJourneysRoute: typeof AdminJourneysRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsRoute: typeof AdminNewsRoute
  NewsIdRoute: typeof NewsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journeys': {
      id: '/admin/journeys'
      path: '/admin/journeys'
      fullPath: '/admin/journeys'
      preLoaderRoute: typeof AdminJourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminJourneysRoute: AdminJourneysRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsRoute: AdminNewsRoute,
  NewsIdRoute: NewsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
